# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: CuiXgの博客
subtitle: 既然认准了一条路，就不要去打听要走多久。
description: 既然认准了一条路，就不要去打听要走多久。
author: CuiXg
language: zh-Hans
timezone: Asia/Shanghai
email: AndyCuiYTT@163.com
keywords: Andy,AndyCui,AndyCuiYTT,AndyCuiの博客

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://andycui.top #https://andycuiytt.github.io #http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link:
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: true

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions 拓展插件配置
## Plugins: https://hexo.io/plugins/
plugins:
baidusitemap:
  path: baidusitemap.xml
sitemap:
  path: sitemap.xml

# 配置RSS
feed:
  #feed 类型 (atom/rss2)
  type: atom
  #rss 路径
  path: atom.xml
  #在 rss 中最多生成的文章数(0显示所有)
  limit: 0


# 自定义站点内容搜索
# 需要先安装插件：
# npm install hexo-generator-search --save
search:
  path: search.xml
  # 如只想索引文章，可设置为post
  field: all

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next



# Deployment
## Docs: https://hexo.io/docs/deployment.html
# deploy:
#  type: git
#  repository: https://github.com/AndyCuiYTT/AndyCuiYTT.github.io.git
#  branch: master

deploy:
  type: git
  repository:
    github: https://github.com/AndyCuiYTT/AndyCuiYTT.github.io.git
    gitcafe: https://git.coding.net/AndyCuiYTT/AndyCuiYTT.git
  branch: master
  message: blog update

